### ISSUE TITLE
login.tpl

### ISSUE THREAD

**Issue by bossloper** [Nicola1971/BSxFLAT#1]
Nicola. Really appreciate your hard work on this, it looks great. I have a couple of comments.

1) In the login page template there is a placeholder missing that displays the 'Forgot your password?' link.
This is [+OnManagerLoginFormRender+] 
It then needs your magic to style it up.

2) Could you add the site name placeholder to the login page <title> tag. It would help for those that use automated password managers to match the correct browser window. Something like this:
`<title>[+site_name+] - MODx CMF Manager Login</title>`

**Comment by Nicola1971** [comment]
1) Added "forgot password" placeholder (and styles)
2) Added sitename placeholder to the login page title tag

**Comment by bossloper** [comment]
Looks good. Thanks.
