### ISSUE TITLE
Elements Icon

### ISSUE THREAD

**Issue by bossloper** [Nicola1971/BSxFLAT#3]
I was not sure where you got your technical.png from that is used for Elements on the Manager home page. Was it one you made, I could not find it in font awesome?

Would http://fontawesome.io/icon/wrench/ be a good option?
For consistency it could then also be used on the up-coming additions to the tree toolbar for 'Manage Elements'

**Comment by Nicola1971** [comment]
this bootstrap theme is still a beta work in progress (there are too much issues like tree refresh not working)
Welcome Icons are from MODXFlat theme 2.x, but I'm working to replace all icons with fontawesome in 3.0 branch https://github.com/Nicola1971/MODxFLAT-Theme/tree/3.0

**Comment by bossloper** [comment]
Sorry yes I posted against the wrong repository. The above comment applies to your link. Though I see you used wrench for settings. A similar questions is still for the 3.0 version as there will be an icon needed for elements on the tree toolbar.
